# -*- coding: utf-8 -*-
"""FACENET.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10y-KgstPoV-2ZGXMqtUlafJxzAdXW2qp
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import keras
from keras.preprocessing.image import ImageDataGenerator

class loadDataset():
  
  def _init_(self):
    
    train_path = "/content/drive/MyDrive/14-celebrity-faces-dataset/data/train"
    val_path = "/content/drive/MyDrive/14-celebrity-faces-dataset/data/val"
    
    train_data = ImageDataGenerator(rescale = 1./255,shear_range = 0.2,zoom_range = 0.2 , horizontal_flip = True)
    train_data = ImageDataGenerator(rescale = 1./255)

    train_dataset = train_data.flow_from_directory(train_path , target_size = (224,224),bath_size = 32,class_mode = "categorical")
    test_dataset = train_data.flow_from_directory(test_path , target_size = (224,224),bath_size = 32,class_mode = "categorical")

  def DataSet(self):
    return train_dataset , test_dataset

D  = loadDataset()
D.DataSet()

class faceNet():
  pass

def modelTrain():
  pass

def modelTestandSave():
  pass