# -*- coding: utf-8 -*-
"""FACENET.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10y-KgstPoV-2ZGXMqtUlafJxzAdXW2qp
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import tensorflow as tf
import keras
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

class loadDataset():
    
  def _init_(self):
    
    train_path = "/content/drive/MyDrive/CelebDataSet/data/train/"
    test_path   = "/content/drive/MyDrive/celebDataSet/data/val/"

    def rename(data):
      for i in os.listdir(data_path):
        print("directory name:",i)
        k=0

        for j in os.listdir(data_path+i):
          print("image name:",j)
          source_path =data_path + i+ "/" + j 
          dest_path = data_path + i + i + f"_{k}.jpg"
          os.rename(source_path , dest_path)
          k = k + 1
    
    rename(self.train_path)
    rename(self.val_path)
    
    train_data = ImageDataGenerator(rescale = 1./255,shear_range = 0.2,zoom_range = 0.2 , horizontal_flip = True)
    test_data = ImageDataGenerator(rescale = 1./255)
    
    train_dataset = train_data.flow_from_directory(train_path , target_size = (224,224),bath_size = 32,class_mode = "categorical")
    test_dataset = test_data.flow_from_directory(test_path , target_size = (224,224),bath_size = 32,class_mode = "categorical")
    
  def ImgBfrPrep(self,name):
    
    image = Image.open(name)
    return image

  def ImgAftrPrep(self,name):
    x = train_dataset.next()
    fig = plt.figure(figsize=(40,40))
    columns = 5
    rows = 6
    for i in range(1, 30):
      fig.add_subplot(rows, columns, i)
      plt.imshow(x[0][i])
    fig.savefig("/content/drive/MyDrive/Celeb.png")
    plt.show()
    
  def DataSet(self):
    
    return train_dataset , test_dataset

class faceNet():
  pass

def modelTrain():
  pass

def modelTestandSave():
  pass